app:
  auth:
    login-url: /Shibboleth.sso/Login
    logout-url: /Shibboleth.sso/Logout
    auto-create-user: true
    local-dev-mode: false

server:
  port: 8443
  ssl:
    enabled: true
    key-store: file:/etc/pki/tls/keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: tomcat
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/uic-shibboleth.log


management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
